const experts = [
    {name: "Prof. Suzanne Devkota", image: "/public/scientist/Frame_1000004726.png", designation: "Director of Cedars-Sinai Human Microbiome Research Institute", description: "Prof. Suzanne Devkota is a leading expert in microbiome research and its impact on human health, with over 15 years of experience in the field. /nShe is an Associate Professor at Cedars-Sinai Medical Center and the Director of the Microbiome Research Institute. /nProf. Devkota’s groundbreaking work focuses on understanding the role of the gut microbiome in chronic diseases, including inflammatory bowel disease, obesity, and diabetes. /nShe has published extensively in top scientific journals and is a sought-after speaker at international conferences. /nProf. Devkota’s research emphasizes the critical connection between the microbiome and overall health, highlighting the potential for microbiome-based therapies. /nHer insights into how diet and lifestyle influence the gut microbiome align closely with IM8's mission to advance health through innovative diagnostics and personalized medicine. /nProf. Devkota’s expertise in microbiome science will be invaluable in helping IM8 develop cutting-edge solutions to improve health outcomes and foster preventative care."},
    {
        name: "Dr. James L. Green", image: "/public/scientist/Frame_1000004724.png", designation: "Former Chief Scientist of NASA", description: "Dr. James L. Green is the former Chief Scientist of NASA, where he dedicated an impressive 42 years to advancing space science and exploration. /nDuring his tenure, Dr. Green contributed to numerous groundbreaking missions, including the Mars Rover landings, the New Horizons mission to Pluto, and the Juno mission to Jupiter. /nHe played a pivotal role in the development of planetary defense strategies and was instrumental in fostering international collaborations for space research. /nDr. Green's extensive experience in managing large-scale scientific projects and his deep understanding of cutting-edge technologies bring a unique perspective to IM8. /nHis work at NASA also included leveraging space research for health innovations, such as studying the effects of space travel on the human body and accelerated aging. /nHis expertise in scientific innovation and strategic vision will be invaluable in advancing IM8's mission to revolutionize healthcare through precision diagnostics and personalized medicine."
    },
    {
        name: "Dr. David Katz", image: "/public/scientist/Frame_1000004727.png", designation: "Founding Director, Yale-Griffin Prevention Research Center", description: "David L. Katz, MD, MPH, FACPM, FACP, FACLM, is a specialist in Internal Medicine, Preventive Medicine/Public Health, and Lifestyle Medicine, with particular expertise in nutrition. /nHe earned his BA at Dartmouth College (1984); his MD at the Albert Einstein College of Medicine (1988); and his MPH from the Yale University School of Public Health (1993). /nKatz is the founder and former director of Yale University’s Yale-Griffin Prevention Research Center (1998-2019); Past President of the American College of Lifestyle Medicine; Founder of the non-profit True Health Initiative; and Founder of Diet ID, Inc, and Chief Medical Officer for Tangelo. /nHe is a Fellow of the American College of Preventive Medicine; the American College of Physicians; the American College of Lifestyle Medicine; and Morse College, Yale University. /nThe recipient of numerous awards for teaching, writing, and contributions to public health, Katz was a 2019 James Beard Foundation Award nominee in health journalism, is a 2023 recipient of a Lifetime Achievement Award from the Doctors’ World Gala, and has received three honorary doctorates. /nHe holds multiple US patents; has roughly 250 peer-reviewed publications; and has authored/co-authored 19 books to date including multiple editions of leading textbooks in nutrition, preventive medicine, and epidemiology."
    },
    {
        name: "Dr. Dawn Mussallem", image: "/public/scientist/sab_Dawn_bio.jpeg", designation: "Integrative Oncologist at Mayo Clinic", description: "Dr. Dawn Mussallem is a distinguished consultant in the Division of Hematology Oncology at Mayo Clinic, where she has served as a clinician for over 20 years, and an Assistant Professor of Medicine. /nShe is a board-certified lifestyle medicine breast specialist at The Robert and Monica Jacoby Center for Breast Health and founded the Integrative Medicine and Breast Health Program at Mayo Clinic Florida. /nA stage IV cancer survivor diagnosed three months into medical school, Dr. Mussallem’s personal journey is a testament to resilience and determination. /nIn 2021, she underwent a heart transplant and remarkably became the first person to run a marathon one year post-transplant. /nInternationally recognized for her work in cancer prevention and integrative oncology, she is a prolific speaker and author. /nHer dedication to patient care and innovative approaches align perfectly with IM8's mission, making her an invaluable addition to the Medical Advisory Board."
    },
    {
        name: "Prof. Stephen Anton", image: "/public/scientist/Frame_1000004725.png", designation: "Professor in the Department of Physiology and Aging at University of Florida", description: "Prof. Stephen Anton is a renowned expert in aging and metabolic health, with over 20 years of experience in the field. He is a Distinguished Professor at the University of Florida with a primary appointment in the Department of Physiology and Aging. Prof. Anton’s research focuses on the interplay between lifestyle factors, metabolic health, and aging, with a particular emphasis on the benefits of caloric restriction, intermittent fasting, and physical activity. /nHe has authored numerous scientific publications and is a frequent speaker at national and international conferences. /nProf. Anton’s extensive work highlights the potential of lifestyle interventions in promoting healthy aging and preventing metabolic diseases. /nHis insights into the mechanisms of aging and metabolic regulation are highly relevant to IM8's mission of leveraging advanced diagnostics and personalized health strategies. /nProf. Anton’s expertise is invaluable in helping IM8 develop innovative solutions to enhance healthspan and improve metabolic health outcomes."
    },
    {
        name: "Dr. James DiNicolantonio", image: "/public/scientist/sab_DiNicolantonio_bio.png", designation: "Cardiovascular Research Scientist and Doctor of Pharmacy", description: "Dr. James DiNicolantonio is a cardiovascular research scientist and Doctor of Pharmacy, known for his influential work in the field of heart health and evidence-based nutrition. Author of several bestselling books, including The Obesity Fix and Superfuel, he has published over 300 scientific papers, focusing on the impact of nutrition on long-term health and chronic disease prevention. His work provides valuable insights into optimizing well-being through natural and scientifically supported methods. /nA respected authority in the health and wellness community, Dr. DiNicolantonio’s approach centers on simplifying complex scientific concepts, making health strategies accessible to a broad audience. He advocates for a proactive approach to wellness, combining cutting-edge research with practical applications to help individuals achieve peak physical and mental performance. His focus on heart health and longevity has made him a key figure for those looking to improve their overall well-being through informed lifestyle choices."
    },
    {
        name: "Dr. Jeremy London", image: "/public/scientist/sab_London_bio.jpeg", designation: "Board Certified Cardiovascular Surgeon", description: "Dr. Jeremy London is a distinguished cardiothoracic surgeon renowned for his expertise in cardiac surgery and minimally invasive procedures. With 26 years of experience treating complex heart conditions, Dr. London emphasizes personalized patient care and integrates advanced surgical techniques to optimize cardiovascular health and recovery. /nRecognized for his compassionate and patient-centered approach, Dr. London excels at translating complex cardiac procedures into clear, understandable guidance, empowering patients to actively participate in their care. Dr. London’s commitment to excellence and his dedication to patient education have established him as a trusted figure in the health and wellness community, helping individuals achieve healthier, happier lives."
    },
    {
        name: "Dr. Amy Shah", image: "/public/scientist/sab_Shah_bio.jpeg", designation: "Double-Board Certified Physician & Host of Podcast “Save Yourself”", description: "Dr. Amy Shah is a double board-certified MD specializing in integrative medicine and a nutrition specialist. She works in clinical medicine, allergy/immunology, and over the last 10 years has developed a world-renowned wellness education platform, successfully launched a growing collection of health and wellness products, written bestselling books, including I’m So Effing Hungry and I’m So Effing Tired, and has made numerous national network appearances. She works to discover less invasive interventions, promote wellness, and teach others how to impact their health via nutrition and exercise -- using medication as a last resort. Her goal is to empower people to “save themselves” through nutrition and lifestyle changes. /nPassionate about helping people take control of their health, Dr. Shah offers a wealth of knowledge on how to optimize vitality through nutrition, fasting, and lifestyle adjustments. Her expertise in gut health and hormone balance has made her a sought-after figure for individuals seeking to enhance their health naturally. Dr. Shah’s balanced, mindful approach resonates with a growing community of wellness enthusiasts who prioritize longevity and sustainable, science-based health practices."
    },
    {
        name: "Dr. Ara Suppiah", image: "/public/scientist/sab_Suppiah_bio.jpeg", designation: "Performance Strategist, Sports Physician, Creator of Functional Sports Medicine", description: "Dr. Ara Suppiah is a globally respected sports physician and performance strategist known for helping elite athletes perform at their highest level—consistently, intelligently, and without burning out. /nBorn in Malaysia, trained in the UK, and now based in the U.S., Ara blends deep medical expertise with cutting-edge tools from neuroscience, functional medicine, genetics, biomechanics, and AI. He’s worked with 7 World No.1s, 35 major golf wins, Olympic medalists, and multiple Ryder Cup teams. As Head of Medical Services for LIV Golf, he’s building world-class systems to keep the game's best at the top of theirs. /nHe created the Functional Sports Medicine Matrix, a systems-based framework to optimize recovery, energy, resilience, and performance. Through his Masterclass and consulting, he teaches other professionals how to think in systems—not symptoms. /nDespite his global reputation, Dr. Ara still works as an ER physician in Orlando and mentors the next generation of clinicians as an assistant professor at the University of Central Florida. /nHis mission is big: to empower one million athletes using the best of authentic intelligence + artificial intelligence."
    },
    {
        name: "Dr. Darshan Shah", image: "/public/scientist/sab_DarshanShah_bio.jpeg", designation: "Board Certified Surgeon & Physician, CEO and Founder of Next Health", description: "Darshan Shah, MD, is a health and wellness specialist, board-certified surgeon, published author, and founder of Next Health, the world's first and largest Health Optimization and Longevity clinic. Dr. Shah is a board certified surgeon who has performed over 20,000 surgical procedures, including trauma and complex reconstructive procedures. As a Longevity Medicine specialist, he has advised thousands of patients on how to optimize their well-being and extend their healthspan and lifespan. /nDr. Shah began his career at an accelerated MD program and earned his medical degree at the age of 21, becoming one of the youngest doctors in the United States. He continued his training at the Mayo Clinic, one of the most prestigious medical institutes in the country. /nAfter earning his board certification, he opened medical/surgical centers throughout California, started four other companies in the Health and Wellness space, and has published a book, authored numerous papers and patented medical devices. /nDr. Shah’s belief in continual education and self-improvement has earned him alumni status at Harvard Business School, Singularity University, and other prestigious institutions. His passion is educating people on the topics of adding healthspan to your lifespan, having done over 100+ speaking engagements and hosting the critically acclaimed podcast Extend."
    },
    {
        name: "Simon Hill", image: "/public/scientist/sab_Hill_bio_1.jpeg", designation: "Nutritionist, Physiologist, and Podcaster", description: "Simon Hill, a physiotherapist and nutrition scientist, is dedicated to simplifying health and nutrition information. He began his career interested in the physiology and anatomy related to optimal athletic performance. Then, encouraged by his Dad’s heart attack, he turned his attention to nutrition’s role in preventing disease and optimising health. Concerned about misleading wellness industry trends, he completed a Master of Science in Human Nutrition at Deakin University. /nToday, Simon hosts a podcast featuring experts translating research into practical advice. He authored “The Proof is in the Plants,” advocating for a plant-rich diet based on current nutrition research. /nOn it’s debut week The Proof is in the Plants was the #1 non-fiction book in Australia. He continues to deepen his understanding of human health by being actively involved in research investigating the links between nutrition and mental health. /nHis podcast, The Proof, a space where he sits down with domain-specific experts, has surpassed 40 million listens, exploring various lifestyle factors impacting well-being. Simon now conducts immersive longevity experiences, aiming to empower people to live better for longer. "
    },
]